port: 3000

logLevel: "debug"

teslaCamFolder: "/mnt/usbfs"
mountTeslaCamFolder: true

archiveFolder: "/archive"
archiveRecent: false
archiveSaved: false
archiveInterval: 60
uploadInterval: 60

uploader: "blobStorage" # "blobStorage", "fileSystem"

fileSystemFileUploader:
  path: "/mnt/nfs"
  requiresMount: false

blobStorageFileUploader:
  accountName: "mlcloudshell"
  accountKey: "GTtwDUEUP/KA7XJAyOPCs8R/h+qoLr88U38xIka0hVsyN3nKb2Ydf5///KEz2pjLqSocGEa7o84d6RhfbPXuuw=="
  containerName: "teslacam"