port: 3000

logLevel: "debug"

teslaCamFolder: "/mnt/usbfs"
mountTeslaCamFolder: true
archiveFolder: "/archive"

archiveRecent: false
archiveSaved: false
archiveInterval: 900
uploadInterval: 300

fileSystemFileUploader:
  path: "/mnt/nfs"
  requiresMount: false