port: 3000

logLevel: "debug"

teslaCamFolder: "/mnt/usbfs"
teslaCamFolderIsMount: false
archiveFolder: "/Users/michiel/test"

archiveRecent: false
archiveSaved: false
archiveInterval: 900
uploadInterval: 300

fileSystemFileUploader:
  path: "/mnt/nfs"
  requiresMount: false